import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import ConfettiButton from './confettiButton'
import Theme from './theme'
import NavButtons from './navButtons'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Checkers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <nav>
            <NavButtons links={
              ["/", "/checkers"]
            }/>
            <ul>
              <li><Link href="/">Home</Link></li>
              <li><Link href="./checkers">Checkers</Link></li>
            </ul>
          </nav>
          {children}
        </Theme>
      </body>
    </html>
  )
}
